const books = [
  {
    id: 1,
    titolo: "Il signore degli anelli",
    autore: "J.R.R. Tolkien",
    anno: 1954,
    genere: "Fantasy",
  },
  {
    id: 2,
    titolo: "Cronache del ghiaccio e del fuoco: Il Trono di Spade",
    autore: "George R.R. Martin",
    anno: 1996,
    genere: "Fantasy",
  },
  {
    id: 3,
    titolo: "1984",
    autore: "George Orwell",
    anno: 1949,
    genere: "Distopia",
  },
  {
    id: 4,
    titolo: "Il giovane Holden",
    autore: "J.D. Salinger",
    anno: 1951,
    genere: "Romanzo",
  },
  {
    id: 5,
    titolo: "Il vecchio e il mare",
    autore: "Ernest Hemingway",
    anno: 1952,
    genere: "Romanzo",
  },
  {
    id: 6,
    titolo: "Harry Potter e la pietra filosofale",
    autore: "J.K. Rowling",
    anno: 1997,
    genere: "Fantasy",
  },
  {
    id: 7,
    titolo: "Moby Dick",
    autore: "Herman Melville",
    anno: 1851,
    genere: "Romanzo",
  },
  {
    id: 8,
    titolo: "Orgoglio e pregiudizio",
    autore: "Jane Austen",
    anno: 1813,
    genere: "Romanzo",
  },
  {
    id: 9,
    titolo: "Cime tempestose",
    autore: "Emily Brontë",
    anno: 1847,
    genere: "Romanzo",
  },
  {
    id: 10,
    titolo: "Don Chisciotte della Mancia",
    autore: "Miguel de Cervantes",
    anno: 1605,
    genere: "Romanzo",
  },
  {
    id: 11,
    titolo: "Il grande Gatsby",
    autore: "F. Scott Fitzgerald",
    anno: 1925,
    genere: "Romanzo",
  },
  {
    id: 12,
    titolo: "Città di carta",
    autore: "John Green",
    anno: 2008,
    genere: "Romanzo",
  },
  {
    id: 13,
    titolo: "Le avventure di Tom Sawyer",
    autore: "Mark Twain",
    anno: 1876,
    genere: "Romanzo",
  },
  {
    id: 14,
    titolo: "Anna Karenina",
    autore: "Lev Tolstoj",
    anno: 1877,
    genere: "Romanzo",
  },
  {
    id: 15,
    titolo: "Il nome della rosa",
    autore: "Umberto Eco",
    anno: 1980,
    genere: "Romanzo storico",
  },
  {
    id: 16,
    titolo: "Delitto e castigo",
    autore: "Fëdor Dostoevskij",
    anno: 1866,
    genere: "Romanzo",
  },
  {
    id: 17,
    titolo: "Le cronache di Narnia: Il leone, la strega e l'armadio",
    autore: "C.S. Lewis",
    anno: 1950,
    genere: "Fantasy",
  },
  {
    id: 18,
    titolo: "Il processo",
    autore: "Franz Kafka",
    anno: 1925,
    genere: "Romanzo",
  },
  {
    id: 19,
    titolo: "Piccole donne",
    autore: "Louisa May Alcott",
    anno: 1868,
    genere: "Romanzo",
  },
  {
    id: 20,
    titolo: "Il vecchio che leggeva romanzi d'amore",
    autore: "Luis Sepúlveda",
    anno: 1989,
    genere: "Romanzo",
  },
  {
    id: 21,
    titolo: "Lo Hobbit",
    autore: "J.R.R. Tolkien",
    anno: 1937,
    genere: "Fantasy",
  },
  {
    id: 22,
    titolo: "La ragazza di fuoco",
    autore: "Suzanne Collins",
    anno: 2009,
    genere: "Fantascienza",
  },
  {
    id: 23,
    titolo: "Il ritratto di Dorian Gray",
    autore: "Oscar Wilde",
    anno: 1890,
    genere: "Romanzo",
  },
  {
    id: 24,
    titolo: "Guerra e pace",
    autore: "Lev Tolstoj",
    anno: 1869,
    genere: "Romanzo storico",
  },
  {
    id: 25,
    titolo: "Il ladro di fulmini",
    autore: "Rick Riordan",
    anno: 2005,
    genere: "Fantasy",
  },
  {
    id: 26,
    titolo: "Il castello",
    autore: "Franz Kafka",
    anno: 1926,
    genere: "Romanzo",
  },
];

module.exports = books;
